# Generated by Django 6.0.5 on 2026-06-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='order_data',
            new_name='ordered_date',
        ),
    ]
