# Generated by Django 4.2 on 2026-06-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_rename_order_data_orderplaced_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='division',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Rangpur', 'Rangpur'), ('Rajshahi', 'Rajshahi'), ('khulna', 'khulna'), ('chttogram', 'chttogram')], max_length=43),
        ),
    ]
